### ISSUE TITLE
Exception in thread "main" java.lang.Exception: org.apache.spark.sql.AnalysisException: Multiple sources found for jdbc (org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider, org.apache.spark.sql.execution.datasources.jdbc.DefaultSource), please specify the fully qualified class name.

### ISSUE THREAD

**Issue by learn-xuan** [InterestingLab/waterdrop#585] opened 2020-11-19 07:58 UTC
**Waterdrop Version(Waterdrop版本)**
1.5.1
A clear version of Waterdrop. 

**Flink or Spark Version(Flink 或者 Spark 版本)**
spark2.3
A clear version of Flink or Spark.

**Java or Scala Version(Java或者Scala版本)**
java version "1.8.0_251"
A clear version of Java or Scala.

**Waterdrop Config(Waterdrop配置文件)**

Please delete sensitive information(请注意删除敏感信息)

spark {
  spark.app.name = "Waterdrop"
  spark.executor.instances = 6
  spark.executor.cores = 6
  spark.executor.memory = "10g"

}

input {
        jdbc {
                driver = "com.mysql.jdbc.Driver"
                url = "jdbc:mysql://***.***.**.**:3306/database"
                table = "table"
                result_table_name = "resultTable"
                user = "user"
                password = "passwd"
                jdbc.partitionColumn = "data_label"
                jdbc.numPartitions = "10"
                jdbc.lowerBound = 0
                jdbc.upperBound = 100
        }
}

filter {
 
}

output {
        hdfs {
                result_table_name = "resultTable"
                path = "hdfs://***.***.***.***:8022/user/test/access.log"
        }
}

**Running Command(启动命令)**

请在这里添加完整的waterdrop启动命令及其参数。
./bin/start-waterdrop.sh --master 'local[6]' --deploy-mode client --config ./config/test.conf
**Error Exception**
Add exception about the problem here.(您可以将程序报错信息粘贴在此处)

![image](https://user-images.githubusercontent.com/49937023/99637539-f8e67c80-2a7f-11eb-87d2-f9f7d0f108ff.png)

**Screenshots**
If applicable, add screenshots to help explain your problem.（您可以将相关截图放在此处）

**Comment by garyelephant** [comment] 2020-11-20 02:11
close this issue due to duplicate of https://github.com/InterestingLab/waterdrop/issues/586

**Closed** 2020-11-20 02:11 UTC
Labels: help wanted
